### ISSUE TITLE
Function store / suggestion

### ISSUE THREAD

**Issue by alexellis** [distantcam/csharp-httprequest-template#1]
Hi @distantcam,

This looks like a nice start.

How about submitting this to the template store for OpenFaaS so that the whole community can make use of it? The only thing I'd ask is that you rename webrequest to "HttpRequest" -> `csharp-httprequest`.

Find out more here -> https://github.com/openfaas/store and here -> https://www.openfaas.com/blog/template-store/

Alex

**Comment by kylos101** [comment]
Hi there,

This template is currently available in the store. Thank you very much!
